title: Sims-Security
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "Sims-Security"
  email: "nomorecontactingplease@thanks-appreciate.com"
  url: "https://blog.sims-security.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Sims-Security"
year : "2021"
